server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:

  datasource:
    # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://kkkamza.c7m2q0i8e4qd.eu-north-1.rds.amazonaws.com/kkkamza
    username: root
    password: kiop3150

  #     H2
  #      url:
  #      username:
  #      password:
  #      driver-class-name: org.h2.Driver

  thymeleaf:
    prefix: classpath:/templates/    # 템플릿 경로
    suffix: .html                     # 파일 확장자
    cache: false # 개발중 cash 비활성화

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

  web:
    resources:
      static-locations: classpath:/static/,file:/static/

logging.level.org.hibernate:
  SQL: debug
#  org.hibernate.type: trace
